-- Agrega tipo/región (para los filtros existentes del catálogo) y carga sus valores
alter table productos add column if not exists tipo text;
alter table productos add column if not exists region text;

update productos set tipo = 'equipo', region = 'españa' where nombre = 'Real Madrid · Titular 25/26';
update productos set tipo = 'retro', region = 'españa' where nombre = 'Real Madrid · Retro 2008';
update productos set tipo = 'seleccion', region = 'sudamerica' where nombre = 'Argentina · Titular 25/26';
update productos set tipo = 'seleccion', region = 'sudamerica' where nombre = 'Argentina · Visitante 25/26';
update productos set tipo = 'retro seleccion', region = 'sudamerica' where nombre = 'Argentina · Edición especial';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Alemania · Visitante 25/26';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Alemania · Tercera 25/26 Black';
update productos set tipo = 'seleccion', region = 'europa españa' where nombre = 'España · Visitante 25/26';
update productos set tipo = 'retro equipo', region = 'england' where nombre = 'Manchester United · Titular 08 Manga Larga Ronaldo 7';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Liverpool · Titular 25/26 Champions';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Liverpool · Titular 25/26';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Liverpool · Visitante 25/26';
update productos set tipo = 'retro equipo', region = 'england' where nombre = 'Manchester City · Tercera 2024';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Manchester City · Titular 2025';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Manchester City · Tercera 2025';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Italia · Titular 2025';
update productos set tipo = 'seleccion sale', region = 'sudamerica' where nombre = 'Colombia · Edición especial';
update productos set tipo = 'equipo', region = 'francia' where nombre = 'PSG · Titular 2025';
update productos set tipo = 'retro equipo', region = 'españa' where nombre = 'Barcelona · Retro 1994 Ronaldo 9';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Nottingham Forest · Titular 25/26';
update productos set tipo = 'seleccion', region = 'sudamerica' where nombre = 'Brasil · Titular 26/27';
update productos set tipo = 'retro equipo', region = 'sudamerica' where nombre = 'Santos · Titular 2011';
update productos set tipo = 'equipo', region = 'sudamerica' where nombre = 'Flamengo · Visitante 26/27';
update productos set tipo = 'equipo sale', region = 'sudamerica' where nombre = 'Corinthians · Titular 25 Memphis 10';
update productos set tipo = 'seleccion sale', region = 'sudamerica' where nombre = 'Colombia · Titular 2024';
update productos set tipo = 'seleccion', region = 'norteamerica' where nombre = 'USA · Titular 2025';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Arsenal · Tercera 2025';
update productos set tipo = 'equipo', region = 'mls' where nombre = 'Inter Miami · Titular 25/26';
update productos set tipo = 'equipo sale', region = 'sudamerica' where nombre = 'Palmeiras · Titular 24/25';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Alemania · Titular 25/26';
update productos set tipo = 'equipo', region = 'francia' where nombre = 'PSG · Visitante 25/26';
update productos set tipo = 'retro equipo', region = 'españa' where nombre = 'Barcelona · Tercera 19/20 · Messi 10';
update productos set tipo = 'equipo', region = 'uruguay' where nombre = 'Nacional Uruguay · Titular';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Portugal · Visitante 25/26';
update productos set tipo = 'equipo', region = 'italia' where nombre = 'AC Milan · Titular 24/25';
update productos set tipo = 'equipo', region = 'españa' where nombre = 'Barcelona · Titular 24/25';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Francia · Titular 25/26';
update productos set tipo = 'retro equipo', region = 'england' where nombre = 'Liverpool · Retro Adidas';
update productos set tipo = 'retro seleccion', region = 'sudamerica' where nombre = 'Brasil · Retro 2004 · Kaká 8';
update productos set tipo = 'equipo', region = 'españa' where nombre = 'Barcelona · Travis Scott';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Inglaterra · Titular 25/26';
update productos set tipo = 'retro seleccion', region = 'asia' where nombre = 'Japón · Retro 2000';
update productos set tipo = 'retro equipo', region = 'francia' where nombre = 'PSG · Retro 16/17 · Neymar';
update productos set tipo = 'equipo', region = 'españa' where nombre = 'Barcelona · Kobe Negro';
update productos set tipo = 'seleccion', region = 'norteamerica' where nombre = 'México · Visitante 2026';
update productos set tipo = 'retro seleccion', region = 'caribe' where nombre = 'Jamaica · Retro Verde';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Inglaterra · Tercera 25/26';
update productos set tipo = 'retro equipo', region = 'españa' where nombre = 'Barcelona · Retro 10/11 · Unicef';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Bélgica · Titular 2022';
update productos set tipo = 'retro equipo', region = 'españa' where nombre = 'Real Madrid · Retro 80s';
update productos set tipo = 'seleccion', region = 'sudamerica' where nombre = 'Argentina · Visitante 2026';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Chelsea · Titular 24/25';
update productos set tipo = 'seleccion', region = 'sudamerica' where nombre = 'Brasil · Visitante Jordan';
update productos set tipo = 'equipo', region = 'italia' where nombre = 'Inter Milan · Titular 24/25';
update productos set tipo = 'equipo', region = 'italia' where nombre = 'Inter Milan · Visitante 24/25';
update productos set tipo = 'equipo', region = 'argentina' where nombre = 'Boca Juniors · 120 Aniversario';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Arsenal · Titular Manga Larga';
update productos set tipo = 'equipo', region = 'arabia' where nombre = 'Al Nassr · Visitante Manga Larga';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Portugal · Titular 25/26';
update productos set tipo = 'equipo', region = 'uruguay' where nombre = 'Peñarol · Titular';
update productos set tipo = 'equipo', region = 'españa' where nombre = 'Real Betis · × Naruto';
update productos set tipo = 'equipo', region = 'sudamerica' where nombre = 'Palmeiras · Titular 25/26';
update productos set tipo = 'seleccion', region = 'sudamerica' where nombre = 'Chile · Titular';
update productos set tipo = 'equipo', region = 'arabia' where nombre = 'Al Nassr · Titular';
update productos set tipo = 'seleccion', region = 'africa' where nombre = 'Nigeria · Visitante';
update productos set tipo = 'equipo', region = 'españa' where nombre = 'Atlético Madrid · Visitante';
update productos set tipo = 'equipo', region = 'francia' where nombre = 'PSG · Titular 23/24';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Francia · Titular 25/26 · Nº7';
update productos set tipo = 'retro seleccion', region = 'europa' where nombre = 'Francia · Retro 1998 · Zidane 10';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Italia · Titular 24/25';
update productos set tipo = 'seleccion', region = 'norteamerica' where nombre = 'México · Titular';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'España · Titular 2022';
update productos set tipo = 'retro equipo', region = 'england' where nombre = 'Manchester United · Retro Visitante 98';
update productos set tipo = 'equipo', region = 'españa' where nombre = 'Barcelona · Visitante 24/25';
update productos set tipo = 'seleccion', region = 'caribe' where nombre = 'Jamaica · Titular';
update productos set tipo = 'equipo', region = 'mls' where nombre = 'Inter Miami · Visitante';
update productos set tipo = 'retro seleccion', region = 'europa' where nombre = 'Inglaterra · Retro 1990';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Tottenham · Visitante';
update productos set tipo = 'retro equipo', region = 'italia' where nombre = 'Juventus · Retro 99 · Manga Larga';
update productos set tipo = 'equipo', region = 'italia' where nombre = 'Juventus · Titular 24/25';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Chelsea · Visitante 24/25';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Holanda · Visitante Mundial 2026';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Liverpool · Titular 24/25 · Mac Allister';
update productos set tipo = 'equipo', region = 'italia' where nombre = 'Napoli · Titular 24/25';
update productos set tipo = 'seleccion', region = 'sudamerica' where nombre = 'Uruguay · Titular 2026';
update productos set tipo = 'retro equipo', region = 'españa' where nombre = 'Barcelona · Retro 14/15 · Qatar';
update productos set tipo = 'equipo', region = 'españa' where nombre = 'Racing Santander · Titular';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Italia · Visitante 25/26';
update productos set tipo = 'retro equipo', region = 'england' where nombre = 'Manchester United · Retro Titular 98';
update productos set tipo = 'seleccion', region = 'asia' where nombre = 'Corea del Sur · Visitante';
update productos set tipo = 'equipo', region = 'england' where nombre = 'Tottenham · Titular';
update productos set tipo = 'seleccion', region = 'europa' where nombre = 'Noruega · Titular Jugador';